[project]
name = "kenny"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask>=2.0",
    "google>=3.0.0",
    "google-generativeai>=0.4.0",
    "numpy>=2.0.2",
    "polars>=0.18.0",
    "requests>=2.32.5",
]
