[project]
name = "kenny"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.1.2",
    "google>=3.0.0",
    "google-generativeai>=0.8.5",
    "numpy>=2.0.2",
    "polars>=1.35.1",
]
